### ISSUE TITLE
Permission Denied when ninja

### ISSUE THREAD

**Issue by sjtuzwj** [SEL4PROJ/sel4-tutorials#42]
![捕获](https://user-images.githubusercontent.com/32933716/71389972-6fdd8000-2639-11ea-8eed-4c292c2ac0dc.JPG)
The tutorials ahead of threads had no problems，however，when I ran threads/IPC，the error occured. 
"rm -rf threads_build" makes no sense.

**Comment by sjtuzwj** [comment]
![捕获](https://user-images.githubusercontent.com/32933716/71390443-60f7cd00-263b-11ea-83f1-ff8bac60f04b.JPG)
After exiting the container, it seems like ninja generate some files only accessible in the host machine. I think this is the source of error.

**Comment by kent-mcleod** [comment]
Hi @sjtuzwj, when changing between your host user and docker container user sometimes the file permissions get set so that one side can't access the other.  When this happens you could try reinitialising the tutorial from the docker container to try building, and then using `chmod -R a+rw .` from the docker container to give the host access to the generated tutorials.

**Comment by kent-mcleod** [comment]
Closing due to staleness.  Feel free to re-open if issue persists.
